;定义资源常量
win_long            equ 800 ;窗口长
win_high            equ 600 ;窗口高
init_longth         equ 3 ;蛇的初始长度
food_rgb            equ 00000FFh ; 食物红色
snake_rgb           equ 0000000h ; 蛇黑色
background_rgb      equ 0FFFFFFh ; 背景为白色

score_x             equ 10 ; 分数显示位置x
score_y             equ 10 ; 分数显示位置y
score_rgb           equ 0000000h ; 分数黑色

position_x          equ 10 ; 显示蛇头位置x
position_y          equ 20 ; 显示蛇头位置y
position_rgb        equ 0000000h ; 蛇头黑色